# Project-wide Gradle settings
kotlin.code.style=official
android.useAndroidX=true
android.enableJetifier=true
kotlin.native.ignoreDisabledTargets=true

# Kotlin/Native
kotlin.mpp.enableCInteropCommonization=true

# Enable Gradle configuration cache
org.gradle.configuration-cache=true

# JVM Options
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m